# Generated by Django 3.0.8 on 2020-08-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elimination',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='elimination',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory_location',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory_location',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pme',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pme',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
