# Generated by Django 3.1.1 on 2020-09-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200803_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_info',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
